name: Generate Daily Redeem Code

on:
  schedule:
    - cron: '0 0 * * *'  # Tiap hari jam 00:00 UTC
  workflow_dispatch:     # Bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run redeem generator
        run: node generate-redeem.js

      - name: Commit and push
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add redeem.json
          git commit -m "🌀 Update redeem code $(date +'%Y-%m-%d')" || echo "No changes"
          git push
